// @ts-nocheck — Auto-generated by assistant-ui shadcn registry
import {
  ComposerAddAttachment,
  ComposerAttachments,
  UserMessageAttachments,
} from "@/components/assistant-ui/attachment";
import { MarkdownText } from "@/components/assistant-ui/markdown-text";
import { ToolFallback } from "@/components/assistant-ui/tool-fallback";
import { TooltipIconButton } from "@/components/assistant-ui/tooltip-icon-button";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useAgentStore, type AgentStep } from "@/lib/agent-store";
import {
  ActionBarMorePrimitive,
  ActionBarPrimitive,
  AuiIf,
  BranchPickerPrimitive,
  ComposerPrimitive,
  ErrorPrimitive,
  MessagePrimitive,
  SuggestionPrimitive,
  ThreadPrimitive,
  useAuiState,
  useThreadRuntime,
} from "@assistant-ui/react";
import {
  ArrowDownIcon,
  ArrowUpIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CopyIcon,
  DownloadIcon,
  MoreHorizontalIcon,
  PencilIcon,
  RefreshCwIcon,
  SquareIcon,
  DatabaseIcon,
  SearchIcon,
  AlertTriangleIcon,
  FileTextIcon,
  Loader2Icon,
  ZapIcon,
} from "lucide-react";
import { type FC, useMemo, useEffect, useRef } from "react";

// ── Marker parsing ──────────────────────────────────────────────────────────
// The route.ts SSE consumer embeds markers in the text stream as the agent
// works.  We parse these markers out so we can:
//   1. Show streaming activity steps (tool running / complete animations)
//   2. Push permit/violation data to the global store for the data panel
//   3. Strip markers from the visible text so the user sees clean markdown

const STEP_MARKER = /<!-- STEP:(.*?) -->/g;
const PERMITS_MARKER = /<!-- PERMITS:(.*?) -->/g;
const VIOLATIONS_MARKER = /<!-- VIOLATIONS:(.*?) -->/g;
// Legacy sentinel from the non-streaming endpoint (still supported)
const LEGACY_ACTIVITY = /<!-- PERMITPULSE_ACTIVITY:.*? -->/g;

/** Extract all STEP markers from a text string */
function parseSteps(text: string): AgentStep[] {
  const steps: AgentStep[] = [];
  let match;
  const re = new RegExp(STEP_MARKER.source, "g");
  while ((match = re.exec(text)) !== null) {
    try {
      const data = JSON.parse(match[1]);
      steps.push({ ...data, timestamp: Date.now() });
    } catch { /* skip malformed */ }
  }
  return steps;
}

/** Strip all embedded markers from text so the user sees clean markdown */
function stripMarkers(text: string): string {
  return text
    .replace(STEP_MARKER, "")
    .replace(PERMITS_MARKER, "")
    .replace(VIOLATIONS_MARKER, "")
    .replace(LEGACY_ACTIVITY, "")
    .replace(/^\n+/, ""); // trim leading newlines from stripped markers
}

// ── Tool icon mapping for inline activity ────────────────────────────────────
const TOOL_ICONS: Record<string, { icon: React.ElementType; color: string }> = {
  tool_fetch_permits: { icon: DatabaseIcon, color: "text-blue-500" },
  tool_search_knowledge: { icon: SearchIcon, color: "text-violet-500" },
  tool_fetch_violations: { icon: AlertTriangleIcon, color: "text-amber-500" },
  tool_fetch_permit_details: { icon: FileTextIcon, color: "text-emerald-500" },
};

// ── Domain suggestions ───────────────────────────────────────────────────────

const PERMIT_SUGGESTIONS = [
  {
    title: "Mission district permits",
    description: "Recent filings and activity",
    prompt: "What building permits have been filed in the Mission district recently?",
  },
  {
    title: "Red flags near Valencia St",
    description: "Violations and unsafe notices",
    prompt: "Show me active violations and red flags near 450 Valencia St",
  },
  {
    title: "Highest-value permits",
    description: "Big construction projects",
    prompt: "What are the highest-value building permits filed in SF this year?",
  },
  {
    title: "District 6 approval times",
    description: "Regulatory speed analysis",
    prompt: "What's the average permit approval time in Supervisor District 6?",
  },
];

export const Thread: FC = () => {
  return (
    <ThreadPrimitive.Root
      className="aui-root aui-thread-root @container flex h-full flex-col bg-background"
      style={{
        ["--thread-max-width" as string]: "44rem",
        ["--composer-radius" as string]: "24px",
        ["--composer-padding" as string]: "10px",
      }}
    >
      <ThreadPrimitive.Viewport
        turnAnchor="top"
        className="aui-thread-viewport relative flex flex-1 flex-col overflow-x-auto overflow-y-scroll scroll-smooth px-4 pt-4"
      >
        <AuiIf condition={(s) => s.thread.isEmpty}>
          <ThreadWelcome />
        </AuiIf>

        <ThreadPrimitive.Messages>
          {() => <ThreadMessage />}
        </ThreadPrimitive.Messages>

        <ThreadPrimitive.ViewportFooter className="aui-thread-viewport-footer sticky bottom-0 mx-auto mt-auto flex w-full max-w-(--thread-max-width) flex-col gap-4 overflow-visible rounded-t-(--composer-radius) bg-background pb-4 md:pb-6">
          <ThreadScrollToBottom />
          <Composer />
        </ThreadPrimitive.ViewportFooter>
      </ThreadPrimitive.Viewport>
    </ThreadPrimitive.Root>
  );
};

const ThreadMessage: FC = () => {
  const role = useAuiState((s) => s.message.role);
  const isEditing = useAuiState((s) => s.message.composer.isEditing);
  if (isEditing) return <EditComposer />;
  if (role === "user") return <UserMessage />;
  return <AssistantMessage />;
};

const ThreadScrollToBottom: FC = () => {
  return (
    <ThreadPrimitive.ScrollToBottom render={<TooltipIconButton tooltip="Scroll to bottom" variant="outline" className="aui-thread-scroll-to-bottom absolute -top-12 z-10 self-center rounded-full p-4 disabled:invisible dark:border-border dark:bg-background dark:hover:bg-accent" />}><ArrowDownIcon /></ThreadPrimitive.ScrollToBottom>
  );
};

const ThreadWelcome: FC = () => {
  return (
    <div className="aui-thread-welcome-root mx-auto my-auto flex w-full max-w-(--thread-max-width) grow flex-col">
      <div className="aui-thread-welcome-center flex w-full grow flex-col items-center justify-center">
        <div className="aui-thread-welcome-message flex size-full flex-col justify-center px-4">
          <h1 className="aui-thread-welcome-message-inner fade-in slide-in-from-bottom-1 animate-in fill-mode-both font-semibold text-2xl duration-200">
            What's happening in SF?
          </h1>
          <p className="aui-thread-welcome-message-inner fade-in slide-in-from-bottom-1 animate-in fill-mode-both text-muted-foreground text-xl delay-75 duration-200">
            Ask about permits, violations, or regulatory risk — I'll fetch live data and grow smarter with each query.
          </p>
        </div>
      </div>
      <ThreadSuggestions />
    </div>
  );
};

const ThreadSuggestions: FC = () => {
  return (
    <div className="grid w-full @md:grid-cols-2 gap-2 pb-4">
      {PERMIT_SUGGESTIONS.map((s, i) => (
        <PermitSuggestionButton key={i} {...s} />
      ))}
    </div>
  );
};

const PermitSuggestionButton: FC<{
  title: string;
  description: string;
  prompt: string;
}> = ({ title, description, prompt }) => {
  const runtime = useThreadRuntime();
  return (
    <button
      onClick={() => {
        runtime.append({
          role: "user",
          content: [{ type: "text", text: prompt }],
        });
      }}
      className="fade-in slide-in-from-bottom-2 animate-in fill-mode-both duration-200 h-auto w-full flex-col items-start justify-start gap-1 rounded-3xl border bg-background px-4 py-3 text-left text-sm transition-colors hover:bg-muted flex"
    >
      <span className="font-medium">{title}</span>
      <span className="text-muted-foreground text-xs">{description}</span>
    </button>
  );
};

const Composer: FC = () => {
  return (
    <ComposerPrimitive.Root className="aui-composer-root relative flex w-full flex-col">
      <ComposerPrimitive.AttachmentDropzone render={<div data-slot="composer-shell" className="flex w-full flex-col gap-2 rounded-(--composer-radius) border bg-background p-(--composer-padding) transition-shadow focus-within:border-ring/75 focus-within:ring-2 focus-within:ring-ring/20 data-[dragging=true]:border-ring data-[dragging=true]:border-dashed data-[dragging=true]:bg-accent/50" />}><ComposerAttachments /><ComposerPrimitive.Input
                      placeholder="Send a message..."
                      className="aui-composer-input max-h-32 min-h-10 w-full resize-none bg-transparent px-1.75 py-1 text-sm outline-none placeholder:text-muted-foreground/80"
                      rows={1}
                      autoFocus
                      aria-label="Message input"
                    /><ComposerAction /></ComposerPrimitive.AttachmentDropzone>
    </ComposerPrimitive.Root>
  );
};

const ComposerAction: FC = () => {
  return (
    <div className="aui-composer-action-wrapper relative flex items-center justify-between">
      <div />
      <AuiIf condition={(s) => !s.thread.isRunning}>
        <ComposerPrimitive.Send render={<TooltipIconButton tooltip="Send message" side="bottom" type="button" variant="default" size="icon" className="aui-composer-send size-8 rounded-full" aria-label="Send message" />}><ArrowUpIcon className="aui-composer-send-icon size-4" /></ComposerPrimitive.Send>
      </AuiIf>
      <AuiIf condition={(s) => s.thread.isRunning}>
        <ComposerPrimitive.Cancel render={<Button type="button" variant="default" size="icon" className="aui-composer-cancel size-8 rounded-full" aria-label="Stop generating" />}><SquareIcon className="aui-composer-cancel-icon size-3 fill-current" /></ComposerPrimitive.Cancel>
      </AuiIf>
    </div>
  );
};

const MessageError: FC = () => {
  return (
    <MessagePrimitive.Error>
      <ErrorPrimitive.Root className="aui-message-error-root mt-2 rounded-md border border-destructive bg-destructive/10 p-3 text-destructive text-sm dark:bg-destructive/5 dark:text-red-200">
        <ErrorPrimitive.Message className="aui-message-error-message line-clamp-2" />
      </ErrorPrimitive.Root>
    </MessagePrimitive.Error>
  );
};

const AssistantMessage: FC = () => {
  // Read the full text content as a stable string primitive
  const rawText = useAuiState((s: any) => {
    const content = s.message.content;
    if (!Array.isArray(content)) return "";
    return content
      .filter((p: any) => p.type === "text")
      .map((p: any) => p.text ?? "")
      .join("");
  });

  // Parse streaming activity steps from the embedded markers
  const steps = useMemo(() => parseSteps(rawText), [rawText]);

  // Track which permits/violations we've already pushed to the store
  // to avoid duplicate pushes on re-renders
  const pushedPermitsRef = useRef(0);
  const pushedViolationsRef = useRef(0);

  // Push new permits to the global store as they stream in
  useEffect(() => {
    const re = new RegExp(PERMITS_MARKER.source, "g");
    let match;
    const allPermits: any[] = [];
    while ((match = re.exec(rawText)) !== null) {
      try {
        const data = JSON.parse(match[1]);
        if (Array.isArray(data)) allPermits.push(...data);
      } catch { /* skip */ }
    }
    // Only push permits we haven't pushed yet
    if (allPermits.length > pushedPermitsRef.current) {
      const newPermits = allPermits.slice(pushedPermitsRef.current);
      useAgentStore.getState().addPermits(newPermits);
      pushedPermitsRef.current = allPermits.length;
    }
  }, [rawText]);

  // Push new violations to the global store
  useEffect(() => {
    const re = new RegExp(VIOLATIONS_MARKER.source, "g");
    let match;
    const allViolations: any[] = [];
    while ((match = re.exec(rawText)) !== null) {
      try {
        const data = JSON.parse(match[1]);
        if (data.violations) allViolations.push(...data.violations);
      } catch { /* skip */ }
    }
    if (allViolations.length > pushedViolationsRef.current) {
      const newViolations = allViolations.slice(pushedViolationsRef.current);
      useAgentStore.getState().addViolations(newViolations);
      pushedViolationsRef.current = allViolations.length;
    }
  }, [rawText]);

  // Push steps to the global store for the LiveDataPanel
  const pushedStepsRef = useRef(0);
  useEffect(() => {
    if (steps.length > pushedStepsRef.current) {
      const newSteps = steps.slice(pushedStepsRef.current);
      for (const step of newSteps) {
        useAgentStore.getState().addStep(step);
      }
      pushedStepsRef.current = steps.length;
    }
  }, [steps]);

  // Check if the message is still streaming (has running steps but no answer yet)
  const hasRunningSteps = steps.some((s) => s.status === "running");
  const cleanText = useMemo(() => stripMarkers(rawText), [rawText]);

  return (
    <MessagePrimitive.Root
      className="aui-assistant-message-root fade-in slide-in-from-bottom-1 relative mx-auto w-full max-w-(--thread-max-width) animate-in py-3 duration-150"
      data-role="assistant"
    >
      <div className="aui-assistant-message-content wrap-break-word px-2 text-foreground leading-relaxed">
        {/* Inline streaming activity trail — shows steps animating in real time */}
        {steps.length > 0 && (
          <div className="mb-3 overflow-hidden rounded-xl border border-zinc-100 bg-zinc-50/80 dark:border-zinc-800 dark:bg-zinc-900/60">
            <div className="flex items-center gap-2 border-b border-zinc-100 px-3 py-1.5 dark:border-zinc-800">
              <span className="text-[10px] font-semibold uppercase tracking-widest text-zinc-400 dark:text-zinc-500">
                Agent Activity
              </span>
              {hasRunningSteps && (
                <Loader2Icon className="size-3 animate-spin text-blue-500" />
              )}
              <span className="ml-auto text-[10px] text-zinc-300 dark:text-zinc-600">
                {steps.length} step{steps.length !== 1 ? "s" : ""}
              </span>
            </div>
            <div className="flex flex-col divide-y divide-zinc-100 dark:divide-zinc-800">
              {steps.map((step, i) => {
                const config = TOOL_ICONS[step.tool] ?? {
                  icon: ZapIcon,
                  color: "text-zinc-400",
                };
                const Icon = config.icon;
                const isRunning = step.status === "running";
                const isError = step.status === "error";

                return (
                  <div
                    key={i}
                    className={`flex items-center gap-3 px-3 py-2 animate-in fade-in slide-in-from-bottom-1 duration-200 ${
                      isRunning ? "bg-blue-50/60 dark:bg-blue-950/20" : ""
                    } ${isError ? "bg-red-50/60 dark:bg-red-950/20" : ""}`}
                    style={{ animationDelay: `${i * 60}ms` }}
                  >
                    {isRunning ? (
                      <Loader2Icon className="size-3.5 shrink-0 animate-spin text-blue-500" />
                    ) : (
                      <div className={`flex size-6 shrink-0 items-center justify-center rounded-md ${
                        isError
                          ? "bg-red-50 dark:bg-red-950/40"
                          : step.tool === "tool_fetch_permits"
                            ? "bg-blue-50 dark:bg-blue-950/40"
                            : step.tool === "tool_search_knowledge"
                              ? "bg-violet-50 dark:bg-violet-950/40"
                              : step.tool === "tool_fetch_violations"
                                ? "bg-amber-50 dark:bg-amber-950/40"
                                : "bg-emerald-50 dark:bg-emerald-950/40"
                      }`}>
                        <Icon className={`size-3.5 ${isError ? "text-red-500" : config.color}`} />
                      </div>
                    )}
                    <span className={`flex-1 text-xs ${
                      isRunning
                        ? "text-blue-600 dark:text-blue-400"
                        : isError
                          ? "text-red-600 dark:text-red-400"
                          : "text-zinc-600 dark:text-zinc-400"
                    }`}>
                      {step.label}
                    </span>
                    {step.count != null && step.status === "complete" && (
                      <span className="text-xs tabular-nums text-zinc-400 dark:text-zinc-500">
                        {step.count} records
                      </span>
                    )}
                    {step.red_flags != null && step.red_flags > 0 && (
                      <span className="rounded-full bg-red-100 px-1.5 py-0.5 text-[10px] font-semibold text-red-600 dark:bg-red-900/30 dark:text-red-400">
                        {step.red_flags} red flag{step.red_flags !== 1 ? "s" : ""}
                      </span>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* The actual answer text (with markers stripped out) */}
        <MessagePrimitive.Parts>
          {({ part }) => {
            if (part.type === "text") return <MarkdownText />;
            if (part.type === "tool-call")
              return part.toolUI ?? <ToolFallback {...part} />;
            return null;
          }}
        </MessagePrimitive.Parts>
        <MessageError />
      </div>

      <div className="aui-assistant-message-footer mt-1 ml-2 flex min-h-6 items-center">
        <BranchPicker />
        <AssistantActionBar />
      </div>
    </MessagePrimitive.Root>
  );
};

const AssistantActionBar: FC = () => {
  return (
    <ActionBarPrimitive.Root
      hideWhenRunning
      autohide="not-last"
      className="aui-assistant-action-bar-root col-start-3 row-start-2 -ml-1 flex gap-1 text-muted-foreground"
    >
      <ActionBarPrimitive.Copy render={<TooltipIconButton tooltip="Copy" />}><AuiIf condition={(s) => s.message.isCopied}>
                      <CheckIcon />
                    </AuiIf><AuiIf condition={(s) => !s.message.isCopied}>
                      <CopyIcon />
                    </AuiIf></ActionBarPrimitive.Copy>
      <ActionBarPrimitive.Reload render={<TooltipIconButton tooltip="Refresh" />}><RefreshCwIcon /></ActionBarPrimitive.Reload>
      <ActionBarMorePrimitive.Root>
        <ActionBarMorePrimitive.Trigger render={<TooltipIconButton tooltip="More" className="data-[state=open]:bg-accent" />}><MoreHorizontalIcon /></ActionBarMorePrimitive.Trigger>
        <ActionBarMorePrimitive.Content
          side="bottom"
          align="start"
          className="aui-action-bar-more-content z-50 min-w-32 overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md"
        >
          <ActionBarPrimitive.ExportMarkdown render={<ActionBarMorePrimitive.Item className="aui-action-bar-more-item flex cursor-pointer select-none items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground" />}><DownloadIcon className="size-4" />Export as Markdown
                              </ActionBarPrimitive.ExportMarkdown>
        </ActionBarMorePrimitive.Content>
      </ActionBarMorePrimitive.Root>
    </ActionBarPrimitive.Root>
  );
};

const UserMessage: FC = () => {
  return (
    <MessagePrimitive.Root
      className="aui-user-message-root fade-in slide-in-from-bottom-1 mx-auto grid w-full max-w-(--thread-max-width) animate-in auto-rows-auto grid-cols-[minmax(72px,1fr)_auto] content-start gap-y-2 px-2 py-3 duration-150 [&:where(>*)]:col-start-2"
      data-role="user"
    >
      <UserMessageAttachments />

      <div className="aui-user-message-content-wrapper relative col-start-2 min-w-0">
        <div className="aui-user-message-content wrap-break-word peer rounded-2xl bg-muted px-4 py-2.5 text-foreground empty:hidden">
          <MessagePrimitive.Parts>
            {({ part }) => {
              if (part.type === "text") return <MarkdownText />;
              return null;
            }}
          </MessagePrimitive.Parts>
        </div>
        <div className="aui-user-action-bar-wrapper absolute top-1/2 left-0 -translate-x-full -translate-y-1/2 pr-2 peer-empty:hidden">
          <UserActionBar />
        </div>
      </div>

      <BranchPicker className="aui-user-branch-picker col-span-full col-start-1 row-start-3 -mr-1 justify-end" />
    </MessagePrimitive.Root>
  );
};

const UserActionBar: FC = () => {
  return (
    <ActionBarPrimitive.Root
      hideWhenRunning
      autohide="not-last"
      className="aui-user-action-bar-root flex flex-col items-end"
    >
      <ActionBarPrimitive.Edit render={<TooltipIconButton tooltip="Edit" className="aui-user-action-edit p-4" />}><PencilIcon /></ActionBarPrimitive.Edit>
    </ActionBarPrimitive.Root>
  );
};

const EditComposer: FC = () => {
  return (
    <MessagePrimitive.Root className="aui-edit-composer-wrapper mx-auto flex w-full max-w-(--thread-max-width) flex-col px-2 py-3">
      <ComposerPrimitive.Root className="aui-edit-composer-root ml-auto flex w-full max-w-[85%] flex-col rounded-2xl bg-muted">
        <ComposerPrimitive.Input
          className="aui-edit-composer-input min-h-14 w-full resize-none bg-transparent p-4 text-foreground text-sm outline-none"
          autoFocus
        />
        <div className="aui-edit-composer-footer mx-3 mb-3 flex items-center gap-2 self-end">
          <ComposerPrimitive.Cancel render={<Button variant="ghost" size="sm" />}>Cancel
                              </ComposerPrimitive.Cancel>
          <ComposerPrimitive.Send render={<Button size="sm" />}>Update</ComposerPrimitive.Send>
        </div>
      </ComposerPrimitive.Root>
    </MessagePrimitive.Root>
  );
};

const BranchPicker: FC<BranchPickerPrimitive.Root.Props> = ({
  className,
  ...rest
}) => {
  return (
    <BranchPickerPrimitive.Root
      hideWhenSingleBranch
      className={cn(
        "aui-branch-picker-root mr-2 -ml-2 inline-flex items-center text-muted-foreground text-xs",
        className,
      )}
      {...rest}
    >
      <BranchPickerPrimitive.Previous render={<TooltipIconButton tooltip="Previous" />}><ChevronLeftIcon /></BranchPickerPrimitive.Previous>
      <span className="aui-branch-picker-state font-medium">
        <BranchPickerPrimitive.Number /> / <BranchPickerPrimitive.Count />
      </span>
      <BranchPickerPrimitive.Next render={<TooltipIconButton tooltip="Next" />}><ChevronRightIcon /></BranchPickerPrimitive.Next>
    </BranchPickerPrimitive.Root>
  );
};
